modLoader="javafml"
loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"
issueTrackerURL="https://github.com/Ramen5914/Create-Cobblemon-Industrialized/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Ramen5914/Create-Cobblemon-Industrialized/refs/heads/main/update.json"
displayURL="https://github.com/Ramen5914/Create-Cobblemon-Industrialized"
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="${mod_authors}"
description='''${mod_description}'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cobblemon"
    type="required"
    versionRange="${cobblemon_version_range}"
    ordering="NONE"
    side="BOTH"
